# Generated by Django 4.2.7 on 2023-12-15 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0004_designation_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('locality', models.TextField()),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=20)),
                ('salary_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_day', models.PositiveIntegerField()),
                ('joining_date', models.DateField()),
                ('designation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='master.designation')),
                ('qualification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='master.qualification')),
            ],
        ),
    ]
