# Generated by Django 4.2.7 on 2023-12-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
