# Generated by Django 4.2.7 on 2023-12-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
